inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/*
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Exclude:
    - db/schema.rb

# Not useful compared to e.g. `Metrics/AbcSize`
Metrics/BlockLength:
  Enabled: false

# Not useful compared to e.g. `Metrics/AbcSize`
Metrics/ClassLength:
  Enabled: false


# Not useful compared to e.g. `Metrics/AbcSize`
Metrics/MethodLength:
  Enabled: false

# Not useful compared to e.g. `Metrics/AbcSize`
Metrics/ModuleLength:
  Enabled: false
