services:
- postgresql
language: ruby
before_install:
- gem install bundler:1.17.0
before_script:
- cp config/database.example.yml config/database.yml
- cp .env.example .env
script:
- bin/rails db:setup
- bin/rails db:test:prepare
- bin/rspec
env:
  global:
  - secure: llix9YONHDT3TscW/0U3lkDY2NVoTPrLZ53TCPmDl7mek+2onxKsLzq5qbDR/U4fwAx3KknJfAiAsOiTRj5ADrh0p69X2H2kZnqm+rA2OACgx4zCqyRPe7T1LyM9z8ivmaCGBSoYHUD3vstEqAjNxBl8o801jdFHplROJlgyYjE=
  - secure: vuf76jahHoPHtXY0XKfseE4bO1Gb5ikXoyAZLPW6mqqImY3QvGRd0zdHn2iUamrQ8H1Lnx9QuyyxF/FKhiY27OpObRGyY6Xg8dgC6n0aJ2h8QofeF6ieN1XsC9v2agtuCe6qY0GCh9s1PbV2vnvKuLkg1qNFTj51TOs9sAVXVuE=
  - secure: bAilG6YBURb7/hMI5Wlpp7toVmP3Z3X7Htjw3ol8kbMh0XkuwVApYcsJLV5uKIG4x4OF7JHx60fsrLt11FW9+73uEI+iv9zfOBA0Sq/BGrDlx5NbJOiMD/fRWNHIknLKTzbU8PsFksv3T7d5XoA+0hhsZ1ziSKIF5tXGXTcxP/8=
