services:
  - postgresql
language: ruby
before_install:
  - gem install bundler:1.17.0
before_script:
  - cp config/database.example.yml config/database.yml
  - cp .env.example .env
script:
  - bin/rails db:setup
  - bin/rails db:test:prepare
  - bin/rspec
